server {
    listen 127.0.0.1:8088;
    root html;
    index index.html;
    metrics on;            # lobo-native: /metrics
    memory_budget 128k;    # lobo-native: per request
    large_client_header_buffers 4 64k;

    location / { }
    location = / { }
    location /files/ {
        types { application/octet-stream bin; }
    }
}
